name: Build for iOS

on:
  push:
    branches:
      - main
      - bumpy-jake
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - name: Run build ios
        run: |
          cd react-native && npm i
          cd ios && pod install && cd ..
          npm run build:ios
      - name: Create build directory
        run: mkdir -p react-native/ios/build
      - name: Upload iOS Archive
        uses: actions/upload-artifact@v6
        with:
          name: ios-archive
          path: react-native/ios/build/SwiftChat.xcarchive
